### ISSUE TITLE
Tooltip for the quotes

### ISSUE THREAD

**Issue by debanjan97** [saivarunr/simpson-quote-vscode-plugin#1]
When window width is less, user is unable to see the full quote

**Comment by saivarunr** [comment]
@debanjan97 are you working on this?

**Comment by debanjan97** [comment]
Yes

**Comment by saivarunr** [comment]
Fixed in #2

**Comment by saivarunr** [comment]
http://marketplace.visualstudio.com/items?itemName=saivarunvishal.simpsons-quotes
